### ISSUE TITLE
两颗独立的 TB67H450FNG 驱动步进电机需要同步机制吗？

### ISSUE THREAD

**Issue by zhbi98** [unlir/XDrive#4]
### 概述

通过 TB67H450FNG 的数据手册知道该芯片是仅有一个通道的有刷直流电机驱动芯片，意味着用于驱动两相步进电机需要使用两颗 TB67H450FNG 芯片。

### 疑问

42 步进电机是两相的，所以就需要两颗 TB67H450FNG 芯片交替有序的输出，所以不知道这两颗芯片如何有序同步，或是说输出信号的相位是否需要错开。

很期待能够得到大佬的解答，在此提前谢过能够解惑的大佬。

**Comment by Mountain03** [comment]
直接看源码,能看懂
